### PR TITLE
Add 'integrations delete' capability for AWS and GitHub

### PR DESCRIPTION
**Pull request by rickporter-tuono**
Example output:
```
(new-host-4):~/cloudtruth-cli $ cargo run -q -- integrations -h
cloudtruth-integrations 
Work with CloudTruth integrations

USAGE:
    cloudtruth integrations [SUBCOMMAND]

FLAGS:
    -h, --help       Prints help information
    -V, --version    Prints version information

SUBCOMMANDS:
    delete    Delete specified CloudTruth integration [aliases: del]
    help      Prints this message or the help of the given subcommand(s)
    list      List CloudTruth integrations [aliases: ls]
(new-host-4):~/cloudtruth-cli $ cargo run -q -- integrations ls -v
+-------------+--------+---------------------+
| Name        | Type   | FQN                 |
+-------------+--------+---------------------+
| Rick Porter | Github | GitHub::Rick Porter |
+-------------+--------+---------------------+
(new-host-4):~/cloudtruth-cli $ cargo run -q -- integrations del -h
cloudtruth-integrations-delete 
Delete specified CloudTruth integration

USAGE:
    cloudtruth integrations delete [FLAGS] [OPTIONS] <NAME>

FLAGS:
        --confirm    Avoid confirmation prompt
    -h, --help       Prints help information
    -V, --version    Prints version information

OPTIONS:
    -t, --type <TYPE>    Integration type, only needed to disambiguate integrations with the same name [possible values:
                         aws, github]

ARGS:
    <NAME>    Integration name
(new-host-4):~/cloudtruth-cli $ cargo run -q -- integrations del "Rick Porter"
Delete integration 'Rick Porter'? (y/n) n
Integration 'Rick Porter' not deleted!
(new-host-4):~/cloudtruth-cli $ cargo run -q -- integrations del "Rick Porter"
Delete integration 'Rick Porter'? (y/n) y
Deleted integration 'Rick Porter'
(new-host-4):~/cloudtruth-cli $ cargo run -q -- integrations ls -v
No integrations found
(new-host-4):~/cloudtruth-cli $
```

### CODE REVIEW

**Comment by jeking3** [comment]
Is there a delete `--yes` to enable automation?

**Review by jeking3 — CHANGES_REQUESTED** [review]
Needs a `--yes` option to enable unconditional behavior for automation.

**Comment by rickporter-tuono** [comment]
I have been using a `--confirm` flag to avoid the need to prompt the user, and that is present. Should we change that to `--yes` in all cases?

**Comment by rickporter-tuono** [comment]
Unable to get merge conflicts resolved correctly, so pulled these changes into PR #79.

**Pull request closed without merging**
